project:
  type: website
  output-dir: docs
  resources:
    - "assets/styles.css"
    - "assets/anfi-style.scss"
    - "assets/css/fraunces.css"
    - "assets/css/commissioner.css"

website:
  title: "Andreas Filser"
  site-url: https://afilser.netlify.app/
  description: "Researcher at FDZ-IAB"
  # favicon: 
  page-navigation: true
  #back-to-top-navigation: true
 
  navbar:
    tools:
    - icon: github
      href: https://github.com/filius23
    right:
      - text: About
        aria-label: "About Me"
        href: about/index.qmd
      - text: Courses
        aria-label: "Courses"
        href: courses/index.qmd
      - text: Publications
        aria-label: "Publications"
        href: publications/publications.qmd
      - text: CV
        aria-label: "CV"
        href: cv/Andreas_Filser_cv.pdf
  
  page-footer:  
    left: >-
     &#169; 2026 Andreas Filser &#8729; Made with [Quarto](https://quarto.org), [{{< fa brands r-project >}}](https://cran.r-project.org/) and {{< fa heart >}}
    center: |
      <a class="link-dark me-1" href="https://bsky.app/profile/filsa.bsky.social" title="Bluesky" target="_blank" rel="noopener">{{< fa brands bluesky >}}</a>
      <a class="link-dark me-1" href="https://iab.de/mitarbeiter/?id=5370712" title="Employer Website (IAB)" target="_blank" rel="noopener">{{< fa link >}}</a>
      <a class="link-dark me-1" href="https://scholar.google.de/citations?user=vP7topAAAAAJ" title="Google Scholar" target="_blank"rel="noopener">{{< ai google-scholar >}}</a>
      <a class="link-dark me-1" href="https://github.com/filius23" title="github" target="_blank" rel="noopener">{{< fa brands github >}}</a>
      <a class="link-dark me-1" href="https://orcid.org/0000-0001-5530-3621" title="orcid" target="_blank" rel="noopener">{{< ai orcid >}}</a>
      <a class="link-dark me-1" href="https://www.linkedin.com/in/andreas-filser-85919450/" title="LinkedIn" target="_blank" rel="noopener">{{< fa brands linkedin >}}</a>
      <a class="link-dark me-1" href="https://osf.io/m7nec/" title="OSF" target="_blank" rel="noopener">{{< ai osf >}}</a>

    right: 
      - text: "Contact"
        aria-label: "Contact"
        href: "contact.qmd"
      - text: "License"
        aria-label: "License"
        href: "license.qmd"

format: 
  html:
    theme: 
      - cosmo
      - assets/css/fraunces.css
      - assets/css/commissioner.css
      - assets/anfi-style.scss
    code-link: true
    pagetitle: "{{< meta title >}}"
    lightbox: true
    meta:
      - name: robots
        content: index, follow
      - name: author
        content: "Andreas Filser"
      - name: description
        content: "Personal website of Andreas Filser: publications, projects, and research."
      - name: keywords
        content: "Andreas, Filser, publications, research, family, sociology, parenthood, motherhood penalty, father, labor market, parental leave, paternal leave, demography, IAB, institute for employment research, Arbeitsmarkt- und Berufsforschung, FDZ, Forschungsdatenzentrum"
      - property: og:type
        content: website
      - property: og:title
        content: "Andreas Filser – Research & Publications"
      - property: og:url
        content: "https://afilser.netlify.app/"
      - property: og:image
        content: "https://afilser.netlify.app/assets/og-image.png"
      - property: og:description
        content: "Personal website of Andreas Filser featuring publications, projects, and research."
      - property: twitter:card
        content: summary_large_image
      - property: twitter:site
        content: "@yourTwitterHandle"  # optional
      - property: twitter:title
        content: "Andreas Filser – Research & Publications"
      - property: twitter:description
        content: "Personal website of Andreas Filser featuring publications, projects, and research."
      - property: twitter:image
        content: "https://afilser.netlify.app/assets/og-image.png"

execute: 
  freeze: auto
